{% set name = "pyvista-xarray" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvista-xarray-{{ version }}.tar.gz
  sha256: 748fa86cdafef8840b9b8c52dd2db001a122dfc7e5fbaff1b82e126ddb6bbb98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyvista
    - scooby
    - xarray

test:
  imports:
    - pvxarray
  commands:
    - pip check
    - python -c "import xarray; assert 'pyvista' in xarray.backends.list_engines()"
    - python -c "import pvxarray, xarray; da = xarray.DataArray(); assert hasattr(da, 'pyvista')"
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyvista-xarray
  summary: PyVista DataArray accessors for xarray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - banesullivan
